from enum import Enum

class Severity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"

class IncidentStatus(str, Enum):
    INVESTIGATING = "INVESTIGATING"
    CONFIRMED = "CONFIRMED"
    MITIGATED = "MITIGATED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"

class ConfidenceTier(str, Enum):
    LOW = "LOW"             # 0 - 39%
    MODERATE = "MODERATE"   # 40 - 69%
    HIGH = "HIGH"           # 70 - 84%
    VERY_HIGH = "VERY_HIGH" # 85 - 100%

class EventType(str, Enum):
    CONFIG_CHANGE = "CONFIG_CHANGE"
    CPU_SPIKE = "CPU_SPIKE"
    PACKET_LOSS = "PACKET_LOSS"
    LATENCY_INCREASE = "LATENCY_INCREASE"
    HANDOVER_FAILURE = "HANDOVER_FAILURE"
    CALL_DROP_SURGE = "CALL_DROP_SURGE"
    ROUTER_FAIL = "ROUTER_FAIL"
    AUTH_FAIL = "AUTH_FAIL"
    SIGNAL_DEGRADATION = "SIGNAL_DEGRADATION"
    THROUGHPUT_SATURATION = "THROUGHPUT_SATURATION"
    BUFFER_OVERFLOW = "BUFFER_OVERFLOW"
    BGP_FLAP = "BGP_FLAP"
    USER_COMPLAINT = "USER_COMPLAINT"

class RelationshipType(str, Enum):
    TRIGGER = "TRIGGER"
    PROPAGATES_TO = "PROPAGATES_TO"
    AFFECTS = "AFFECTS"
    CONSEQUENCE = "CONSEQUENCE"
    CORRELATED = "CORRELATED"
    CONCURRENT = "CONCURRENT"

class EvidenceType(str, Enum):
    TEMPORAL_PRECEDENCE = "TEMPORAL_PRECEDENCE"
    TELEMETRY_ANOMALY = "TELEMETRY_ANOMALY"
    TOPOLOGY_BLAST = "TOPOLOGY_BLAST"
    CONFIG_DIFF = "CONFIG_DIFF"
    PROTOCOL_ERROR = "PROTOCOL_ERROR"
    LOG_SIGNATURE = "LOG_SIGNATURE"
    HISTORICAL_ANALOGY = "HISTORICAL_ANALOGY"
